### ISSUE TITLE
Custom outDir and hydration breaks build

### ISSUE THREAD

**Issue by gilesbutler** [ElMassimo/iles#130]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

When using custom `outDir` and hydrated components i.e `<Welcome client:load />` the build fails with the following error: 
```
✖ writing pages
build error:
 [ENOENT: no such file or directory, open '/home/projects/iles-slj6as/temp/build/manifest.json'] {
  code: 'ENOENT',
  errno: -2,
  path: '/home/projects/iles-slj6as/temp/build/manifest.json',
  syscall: 'open'
}
```

### Reproduction 🐞

https://stackblitz.com/edit/iles-slj6as?file=src%2Fpages%2Fabout.vue,src%2Fcomponents%2FWelcome.vue,iles.config.ts

<details>
<summary>Dependencies Info</summary>

_Run `npx iles info` and `pnpm list` (or `npm list`) and provide the output:_

```
iles v0.7.38 vite v2.9.9
```
</details>

### Screenshots 📷

![CleanShot 2022-06-09 at 09 35 18@2x](https://user-images.githubusercontent.com/790734/172734797-3b2dda74-6373-45ce-865f-ef6cc418299b.png)

**Comment by gilesbutler** [comment]
Hey @ElMassimo would love to get your thoughts or inout on this. Happy to do a PR if you can help point me in the right direction 😃

**Comment by ElMassimo** [comment]
Hi Giles! @gilesbutler 

Seems like the `outDir` option is not being used when [building islands](https://github.com/ElMassimo/iles/blob/main/packages/iles/src/node/build/islands.ts#L35-L50). If you run build in your reproduction, you can see that it's still writing in `dist` instead of `temp/build`.

[Setting `outDir` explicitly](https://github.com/ElMassimo/iles/blob/main/packages/iles/src/node/build/bundle.ts#L61) when building islands should fix the problem.

Pull requests are welcome!

**Comment by gilesbutler** [comment]
Awesome, thanks @ElMassimo I'll take a look 👍
