### ISSUE TITLE
Excerpts (@islands/excerpt) aren't reliably extracted during dev

### ISSUE THREAD

**Issue by nixyxo** [ElMassimo/iles#131]
- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

- On a fresh dev instance, with only `modules: ['@islands/excerpt']` added to iles config (and npm installed).
- On first run, excerpt is only added to the first content item (see screenshot).
- After a change to a source file, triggering HMR, any excerpts that were added disappear.
- On stopping and restarting dev instance, excerpt is not added to any content items.

All content appears to be excerpted as expected on running `npm run build` then `npm run preview`.

Aside: I think I once saw `item.excerpt` was set and `item.meta.excerpt` was not set, but I could not reproduce that.

### Reproduction 🐞

https://github.com/nixyxo/iles-excerpt-test

<details>
<summary>Dependencies Info</summary>

```
iles v0.7.38 vite v2.9.10
```

```
iles-app@0.0.0 /Users/nx/iles-excerpt-test/
├── @islands/excerpt@0.1.3
├── iles@0.7.38
├── typescript@4.7.3
└── vue-tsc@0.29.8
```
</details>

### Screenshots 📷

<img width="979" alt="Screen Shot 2022-06-09 at 9 12 00 AM" src="https://user-images.githubusercontent.com/51681029/172958980-e0222dd6-46f4-4236-b438-1bafbefd704f.png">

**Comment by ElMassimo** [comment]
Hi! Thanks for providing a reproduction!

Since the purpose of `useDocuments` is to be able to obtain a reference to a potentially very large collection, forcing the parse of all files would slow down development. If you need that behavior you can use [`import.meta.globEager`](https://iles-docs.netlify.app/guide/documents#documents) to import the pages.

The recommended approach to use an excerpt, is to [render the componentin `excerpt` mode](https://iles-docs.netlify.app/guide/documents#using-data-in-documents).

In [your example](https://github.com/nixyxo/iles-excerpt-test/blob/main/src/pages/content/index.vue#L12):

```
<component :is="item" excerpt/>
```

--- 

The [excerpt is always available in a component instance](https://github.com/ElMassimo/iles/blob/main/packages/excerpt/src/rehype-plugin.ts#L47-L48).

Although the [`vfile.data`](https://github.com/ElMassimo/iles/blob/main/packages/mdx/src/mdx.ts#L37) is also copied over to the page static data, which is [used by `useDocuments`](https://github.com/ElMassimo/iles/blob/main/packages/iles/src/node/plugin/documents.ts#L58), there's no guarantee that a page component has been parsed _**before**_ `useDocuments` is called.

The behavior in this bug report is likely caused by a race condition, depending on when `useDocuments` is processed, each page will or won't have the metadata obtained by `@islands/mdx` when doing a full parse of the file.

This __should__ be in the documentation, keeping this issue opened as a reminder to add a warning tip in the _Documents_ section, so that users don't rely on `meta.excerpt` being available when using documents.

**Comment by ElMassimo** [comment]
This is documented in the [`@islands/excerpt` usage instructions](https://iles-docs.netlify.app/guide/plugins#islandsexcerpt).

**Comment by nixyxo** [comment]
Thank you for the clarification.

I understand and agree with the logic around avoiding `useDocuments` needing to parse all markdown files in a large collection up front during dev.

I am able to use the excerpt prop on the component like in your example. I think that solves my use case. 

I do think the docs around excepts could be clearer about this. E.g. `sets meta.excerpt` is not always true as you noted and I don't think the followup code samples were clear enough (at least to me) around why it works with `usePage()` and won't work with `useDocuments()` unless you use the component instance.

I'll think around if there are any docs edits that would have helped me get the concept better and not trip on expecting meta.excerpt to be set. I'll propose something if I find a good edit.

~~~

Lastly, thanks for making this great tool, overall I've found it to be very friendly and aligned to what I wanted out of a static site generator; I particularly like using Vue template syntax for everything.

**Comment by ElMassimo** [comment]
Thanks! Improvements to the docs are always welcome! We could add a warning `Tip` at the end of the `@islands/excerpt` section warning about this more explicitly.
