### ISSUE TITLE
Page island is rendered in slot of layout island

### ISSUE THREAD

**Issue by davidlueder** [ElMassimo/iles#193]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖
When islands are rendered within a layout file and within a page file, the **page island hydration ids start with ile-1 again**. The second component from the page is rendered in the slot of the layout component (see stackblitz example)

It seems to have something to do with the `newHydrationId()` function but i was not able to find the root cause:
https://github.com/ElMassimo/iles/blob/df8b7935ab1afd2a8b238a3cb93a885c4634f6d1/packages/iles/src/client/app/hydration.ts#L22

### Reproduction 🐞
https://stackblitz.com/edit/iles-ytnhui

`npm run dev` - bug reproducible
`npm run now` - no bug (as expected because `newHydrationId()` uses a different implementation for SSR during build)

### Logs 📜

> [Vue warn]: There is already an app instance mounted on the host container.
 If you want to mount another app on the same host container, you need to unmount the previous app by calling `app.unmount()` first.

**Comment by ElMassimo** [comment]
Hi David, thanks for reporting.

This could be [another case](https://github.com/ElMassimo/iles/issues/192#issuecomment-1238060702) of modules being duplicated by Vite, or a bug in how the counter is reset after navigation.

Would you check if there are two copies of [`client/app/hydration.ts`](https://github.com/ElMassimo/iles/blob/b6f231eb677256cdc575fb33fd534d794558a2c5/packages/iles/src/client/app/hydration.ts) being sent to the browser during development in your site?

**Comment by ElMassimo** [comment]
Gotcha, then it's option 2, thanks for checking.

> But that seems to be the wanted behavior?

The idea behind resetting was to simulate the behavior that would occur during build, where each page starts from `1`.

Since ids are not meant to be relied on by the user, a potential fix is to avoid resetting ids.

---

I don't understand why this bug does not manifest in the docs site, need to check.

Perhaps this has to do with how Vue reuses DOM elements when re-rendering the layout (layout does not change between pages so islands in layout are not re-rendered, so `newHydrationId` is not called until the first page island, which then overlaps with the layout islands).

**Comment by ElMassimo** [comment]
@davidlueder After trying the example, I noticed it only happens when using `router-link`, but [not when using `a`](https://stackblitz.com/edit/iles-rw2r34?file=src%2Flayouts%2Fdefault.vue).

**Comment by ElMassimo** [comment]
> Perhaps this has to do with how Vue reuses DOM elements when re-rendering the layout

That theory turned out to be correct.

Fixed by changing the way ids are recycled during dev: instead of resetting to zero on navigation, we now mark ids as available once islands are unmounted.

As a result, we prevent using ids which are currently taken, but ids still match what you would see during build:

<img width="966" alt="Screen Shot 2022-09-11 at 22 37 34" src="https://user-images.githubusercontent.com/1158253/189559563-181b08cd-b361-4b0a-a54b-e23b9dba53ba.png">

Thanks again for reporting! @davidlueder
