### ISSUE TITLE
PrettyUrls settings appears to be the wrong way around

### ISSUE THREAD

**Issue by ohuu** [ElMassimo/iles#195]
The `prettyUrls` setting appears to be the wrong way around. I would expect routes to be like this `.../products/index.html` when `prettyUrls` is set to `true`. However the routes appear like this `.../products.html` which requires one to explicitly include `.html` at the end of the url

It might just be me but that seems to be the opposite of what you want?

**Comment by ohuu** [comment]
Actually this setting looks to be broken. Dynamic routes appear to be ignored

**Comment by ElMassimo** [comment]
When vendors like Netlify and Vercel say "prettyUrls", they mean `/products` instead of `/products/`.

[Here's an example of a dynamic route with `prettyUrls`](https://iles.pages.dev/dynamic/one), and an example of a [dynamic route with `prettyUrls: false`](https://the-vue-point-with-iles.netlify.app/posts/1.html).

If you open a discussion with a repo example, I can take a look 😃

**Comment by ohuu** [comment]
We're not using Netlify or Vercel to host our site. We're using DigitalOcean's App Platform and all our urls are like this `/products/1.html`. I assumed `prettyUrls` would instruct Iles to create something like this `/products/1/index.html` so that the url would look like this `/products/1`. Is this what Iles is supposed to be doing?

**Comment by ohuu** [comment]
Ahh, that's how it works! Thanks I got it working now.
