### ISSUE TITLE
Unable to apply client directive when using Vuetify

### ISSUE THREAD

**Issue by TechAkayy** [ElMassimo/iles#259]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

I'm using Vuetify, and the SampleCard component in the index page loads fine in development before adding client directives. But when I add `client:load` to SampleCard, vuetify breaks with this error message. 

I notice a slight flash of the component loading fine, before it disappears and displays the below error. 

![image](https://github.com/ElMassimo/iles/assets/73772701/5c0366b3-ae78-47c0-aee9-de2db652cd79)

### Reproduction 🐞

https://github.com/pinegrow/pg-iles-vuetify

<details>
<summary>Dependencies Info</summary>

_Run `npx iles info` and `pnpm list` (or `npm list`) and provide the output:_

```
iles v0.9.5 vite v4.3.9
```
</details>

**Comment by ElMassimo** [comment]
Hi!

Based on the error message, it seems like Vuetify is relying on global injects, requiring it to be installed in the Vue app.

Since `client:load` will run the component in a separate Vue app, you might need to `use` the plugin provided by Vuetify inside the island, see [related discussion](https://github.com/ElMassimo/iles/discussions/6#discussioncomment-4312998).

**Comment by TechAkayy** [comment]
Awesome, thanks @ElMassimo. That makes sense. `import { getCurrentInstance } from 'vue'` is a new learning for me :-)

**Comment by TechAkayy** [comment]
Works nicely now 👍 https://pg-iles-vuetify.netlify.app/ Thanks.
