### ISSUE TITLE
Importing scripts into Iles

### ISSUE THREAD

**Issue by R0N1n-dev** [ElMassimo/iles#272]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [ ] I have read the __[troubleshooting section]__ before opening an issue.
- [ ] I have tried upgrading `iles` and `vite`.

### Description 📖

Cannot get script through cdn
Have been having an issue trying to intergrate Vue Ui libraries especially the ones which contain JS (like Vuesax-alpha, Inkline, WaveuI) into iles.
Using cdn, css comes through but the scripts don't

### Reproduction 🐞

https://stackblitz.com/github/R0N1n-dev/iles-pwa

<details>
<summary>Dependencies Info</summary>

_Run `npx iles info` and `pnpm list` (or `npm list`) and provide the output:_

```
iles v0.9.5 vite v4.4.4

```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

_Run `DEBUG=iles:* npm run dev` or `DEBUG=iles:* npm run build` and provide the output:_

```

```
</details>

![Screenshot from 2024-03-19 16-27-26](https://github.com/ElMassimo/iles/assets/83344872/52d445f0-a34c-42dc-b52a-3187b68ef3dc)

The 'Button' should look like this
![Screenshot from 2024-03-19 16-27-56](https://github.com/ElMassimo/iles/assets/83344872/3acbcee0-4aa7-49ea-9a8f-c05e7632b3b1)

**Comment by TechAkayy** [comment]
Hi there, 

I tried using inkline on a normal Vue project on stackblitz, and I'm seeing some odd errors with their cdn js script. And I tried in your iles repo as well, same error. This looks like an issue with Inkline rather than with Vue/Iles. Best to raise this bug with them. 

Also, their documentation does cover using inkline as a Vite plugin, so that the components can be auto-imported and tree-shaken. Any reason why you are using that way? Iles uses Vite underneath, any Vite plugins can be added to `iles.config.ts` under a `vite` property (https://iles.pages.dev/config#configuring-vite)

https://stackblitz.com/edit/vitejs-vite-fpykgf?file=index.html

<img width="1508" alt="image" src="https://github.com/ElMassimo/iles/assets/73772701/aa93b9cc-d65f-4454-ad65-74d0c6f215ef">

**Comment by TechAkayy** [comment]
Also in your reproduction, if you check console, you will notice that the inkline cdn script & css are added the head as expected. So, extending the head via `app.js` is working the Iles way. If you check the console, you will notice the same error as above in your iles repo too. 

Also, I believe when you use cdn, you will have to stick to kebabcase for components. But, I would recommend you to configure inkline the Vite way as per their docs. 

<img width="1511" alt="image" src="https://github.com/ElMassimo/iles/assets/73772701/2cb72aeb-1774-4f4c-93ca-bb4d69813c82">

**Comment by R0N1n-dev** [comment]
Alright. Thanx
