### ISSUE TITLE
Manual imports for unplugin-icons in client script are not being resolved

### ISSUE THREAD

**Issue by gawlk** [ElMassimo/iles#31]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

Basically the title. On build with vite-svg-loader it'll break and won't build but when importing icons only the build will finish but the icons won't show up. In dev mode there is no error but neither the sag imported nor the icons will show up.

### Reproduction 🐞

_Please provide a link to a repo that can reproduce the problem you ran into._

I'll try to do this ASAP

In the meantime here's the config file

```
import { defineConfig } from 'iles'
import path from 'path'

import svgLoader from 'vite-svg-loader'

export default defineConfig({
  modules: ['@islands/icons'],
  siteUrl: 'https://alfred.rndt.fr',
  vite: {
    resolve: {
      alias: {
        '/src': path.resolve(__dirname, 'src'),
      },
    },
    plugins: [svgLoader()],
  },
})
```

<details>
<summary>Dependencies Info</summary>

_Run `npx iles info` and `pnpm list` (or `npm list`) and provide the output:_

```

```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

_Run `DEBUG=iles:* npm run dev` or `DEBUG=iles:* npm run build` and provide the output:_

```

```
</details>

### Screenshots 📷

_Provide console or browser screenshots of the problem_.

Screenshots of the build mode:

With an svg:

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/32246972/140484404-d24b99d7-dbae-4b7f-800c-59d3797e7efc.png">

With icons only:

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/32246972/140484676-d861a1e4-7a00-4e14-88a6-886f01681387.png">

**Comment by ElMassimo** [comment]
Hi Kevin, please don't open issues without providing the requested information, as it doesn't allow me to investigate why this might be happening.

Please provide the full component code where you are using these icons. You seem to be importing them on client scripts, but that on its own wouldn't render them.

Also, instead of `vite-svg-loader` you could place custom svgs in /icons and use them (`IconAppLogo`), or define a custom collection in unplugin-icons (passing config to the `@islands/icons` module).
