### ISSUE TITLE
FOUC on Firefox

### ISSUE THREAD

**Issue by innocenzi** [ElMassimo/iles#76]
- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

There is [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1404468) in Firefox which causes a flash of unstyled content by displaying the markup, then the CSS. 

A workaround is to add `<script>0</script>` right after `<body>`.

Is there a way to hook into the page generation process to add this workaround?

### Reproduction 🐞

- Use Firefox
- (optional) Throttle your network
- Go to https://the-vue-point-with-iles.netlify.app/
- Observe FOUC
</details>

### Screenshots 📷

On Firefox: 

![](https://i.imgur.com/ShQD2Re.gif)

On Chrome:

![](https://i.imgur.com/PwQGHzB.gif)

**Comment by ElMassimo** [comment]
Hi Enzo!

Firefox has the [weirdest bugs](https://github.com/ElMassimo/iles/issues/51#issuecomment-981085731).

The best place to inject the workaround script tag would be <kbd>[ssg.beforePageRender](https://iles-docs.netlify.app/config#ssg-beforepagerender)</kbd>, right before the page is written to a file.

I'll take a deeper look later, perhaps we can [add the workaround in îles like last time](https://github.com/ElMassimo/iles/issues/51#issuecomment-981094613). Feel free to open a PR!

Amazing that a bug like this has been open for four years.

**Comment by innocenzi** [comment]
Yup, Firefox is weird. Thanks for the hook, I successfully implemented the workaround for now! :)

**Comment by ElMassimo** [comment]
Closing for now, users can workaround this Firefox issue by injecting `<script>0</script>` using the <kbd>[ssg.beforePageRender](https://iles-docs.netlify.app/config#ssg-beforepagerender)</kbd> hook.

---

The FOUC will only happen in Firefox when __all__ the following conditions are met:

- It's the first visit (after that the assets are cached unless _Disable Cache_ is explicitly enabled in devtools)
- On a slow connection

We could add the workaround to iles by default, but perhaps we can wait until this issue is fixed in Firefox.

**Comment by innocenzi** [comment]
I agree that a workaround is not needed in Iles directly, however I think it could be documented in a troubleshooting section, as the problem is quite weird. 

Would you like me to PR?

**Comment by ElMassimo** [comment]
That would be great, thanks!
